apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytevault-deployment
  labels:
    app: bytevault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bytevault
  template:
    metadata:
      labels:
        app: bytevault
    spec:
      containers:
      - name: bytevault
        image: nginx:latest  # This will be replaced by ECR image
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads
      volumes:
      - name: uploads-volume
        emptyDir: {}
